import type { ExamplePreset } from '../../app/workspaceTypes';

const finite = (re: number, im: number) => ({
  kind: 'finite' as const,
  impedanceOhms: { re, im },
});

export const EXAMPLES: readonly ExamplePreset[] = [
  {
    id: 'matched',
    name: 'Matched 50 Ω',
    category: 'fundamentals',
    description: '50 + j0 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'See the matched center and why no stub is required.',
    calculation: {
      load: finite(50, 0),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'short',
    },
    expectedStatus: 'matched',
  },
  {
    id: 'resistive',
    name: 'Pure resistance',
    category: 'fundamentals',
    description: '25 + j0 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'Compare the two symmetric unit-conductance intersections.',
    calculation: {
      load: finite(25, 0),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'short',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'capacitive',
    name: 'Capacitive antenna',
    category: 'fundamentals',
    description: '35 − j22 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'Follow a common capacitive antenna match with a short stub.',
    calculation: {
      load: finite(35, -22),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'short',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'inductive',
    name: 'Inductive antenna',
    category: 'fundamentals',
    description: '35 + j22 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'See positive reactance and an open-stub construction.',
    calculation: {
      load: finite(35, 22),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'open',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'near-open',
    name: 'Near open',
    category: 'edge-cases',
    description: '5000 + j800 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'Inspect a numerically demanding point near the chart boundary.',
    calculation: {
      load: finite(5000, 800),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'open',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'near-short',
    name: 'Near short',
    category: 'edge-cases',
    description: '0.5 + j0.2 Ω on a 50 Ω line at 14.2 MHz.',
    learningGoal: 'Inspect a very low impedance near the chart boundary.',
    calculation: {
      load: finite(0.5, 0.2),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'short',
    },
    expectedStatus: 'solved',
  },
  {
    id: '75-ohm',
    name: '75 Ω system',
    category: 'systems',
    description: '42 − j30 Ω on a 75 Ω line at 10 MHz.',
    learningGoal: 'See normalization in a non-50-ohm reference system.',
    calculation: {
      load: finite(42, -30),
      characteristicImpedanceOhms: 75,
      frequencyHz: 10_000_000,
      velocityFactor: 0.8,
      termination: 'short',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'hf',
    name: '14.2 MHz antenna',
    category: 'systems',
    description: '35 − j22 Ω, 50 Ω coax, VF 0.66, short stub.',
    learningGoal: 'Work through practical HF coax lengths.',
    calculation: {
      load: finite(35, -22),
      characteristicImpedanceOhms: 50,
      frequencyHz: 14_200_000,
      velocityFactor: 0.66,
      termination: 'short',
    },
    expectedStatus: 'solved',
  },
  {
    id: 'vhf',
    name: '146 MHz mobile radio',
    category: 'systems',
    description: '28 + j18 Ω, 50 Ω line, VF 0.78, open stub.',
    learningGoal: 'Compare compact VHF physical lengths with HF lengths.',
    calculation: {
      load: finite(28, 18),
      characteristicImpedanceOhms: 50,
      frequencyHz: 146_000_000,
      velocityFactor: 0.78,
      termination: 'open',
    },
    expectedStatus: 'solved',
  },
] as const;

export const ANTENNA_EXAMPLE = EXAMPLES.find((example) => example.id === 'hf')!;
