import type { ExamplePreset } from '../../app/workspaceTypes';

export const EXAMPLES: readonly ExamplePreset[] = [
  {
    id: 'matched',
    name: 'Matched 50 Ω',
    load: { kind: 'finite', impedanceOhms: { re: 50, im: 0 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'short',
    note: 'Already matched reference load.',
  },
  {
    id: 'resistive',
    name: 'Pure resistance',
    load: { kind: 'finite', impedanceOhms: { re: 25, im: 0 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'short',
    note: 'Two symmetric conductance intersections.',
  },
  {
    id: 'capacitive',
    name: 'Capacitive antenna',
    load: { kind: 'finite', impedanceOhms: { re: 35, im: -22 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'short',
    note: 'Common HF antenna example.',
  },
  {
    id: 'inductive',
    name: 'Inductive antenna',
    load: { kind: 'finite', impedanceOhms: { re: 35, im: 22 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'open',
    note: 'Positive reactance example.',
  },
  {
    id: 'near-open',
    name: 'Near open',
    load: { kind: 'finite', impedanceOhms: { re: 5000, im: 800 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'open',
    note: 'Numerically demanding high impedance.',
  },
  {
    id: 'near-short',
    name: 'Near short',
    load: { kind: 'finite', impedanceOhms: { re: 0.5, im: 0.2 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'short',
    note: 'Numerically demanding low impedance.',
  },
  {
    id: '75-ohm',
    name: '75 Ω system',
    load: { kind: 'finite', impedanceOhms: { re: 42, im: -30 } },
    z0: 75,
    frequencyHz: 10_000_000,
    velocityFactor: 0.8,
    termination: 'short',
    note: 'Non-50-ohm reference system.',
  },
  {
    id: 'hf',
    name: '14.2 MHz antenna',
    load: { kind: 'finite', impedanceOhms: { re: 35, im: -22 } },
    z0: 50,
    frequencyHz: 14_200_000,
    velocityFactor: 0.66,
    termination: 'short',
    note: 'HF coax construction example.',
  },
  {
    id: 'vhf',
    name: '146 MHz mobile radio',
    load: { kind: 'finite', impedanceOhms: { re: 28, im: 18 } },
    z0: 50,
    frequencyHz: 146_000_000,
    velocityFactor: 0.78,
    termination: 'open',
    note: 'VHF physical lengths.',
  },
];
